### ISSUE TITLE
Unzer Pay Later T&C changes

### ISSUE THREAD

**Issue by Fynfner** [QuickPay/standard-branding#104]
We have some minor changes to the window:
* T&C and DP links should be opened in a new tab
* Align T&C acceptance text on the left

**Comment by ziam12** [comment]
When it comes to aligning the text, would you prefer something similar to this?
before
<img width="543" alt="image" src="https://user-images.githubusercontent.com/97883377/179996830-a845350a-92ff-4fa2-81d8-3b84edf96c50.png">

after
<img width="493" alt="image" src="https://user-images.githubusercontent.com/97883377/179996644-a26c31fd-5668-4a4a-8cd7-51b4edff8470.png">

**Comment by ziam12** [comment]
changes already added
