### ISSUE TITLE
Update Faroe translations

### ISSUE THREAD

**Issue by QP-SRT** [QuickPay/standard-branding#139]
We need to make the following changes to the standard-branding:

Navn á kortið - ændres til - Navn á korteigara
Útgongudagur - ændres til - Lokadagur
Gjald - ændres til - Rinda

Hjælpetekst til CVV/CVD:

Trygdartølini (Card Verification Data) økja um trygdina fyri teg sum kunda. Vanliga er hetta eitt nummar, sett saman av trimum tølum, ið eru at finna á baksíðuni á kortinum.

**Comment by benee** [comment]
solved by https://github.com/QuickPay/standard-branding/pull/140
