### ISSUE TITLE
better text for klarna

### ISSUE THREAD

**Issue by ssandgren** [QuickPay/standard-branding#26]
You can enter both cpr and cvr number for klarna, but it only says cpr.

<img width="496" alt="screen shot 2017-08-09 at 10 09 30" src="https://user-images.githubusercontent.com/3764413/29111727-b0c42a1e-7ceb-11e7-9311-1121f6bc338c.png">

**Comment by ta** [comment]
A few questions...

* Are companies/VAT supported by all countries and currencies?
* If using VAT, does "Gender" still apply?

**Comment by ssandgren** [comment]
ikke længere relevant med ny klarna
