### ISSUE TITLE
Display issues when creating a card

### ISSUE THREAD

**Issue by ta** [QuickPay/standard-branding#39]
If the payment window is opened using `/cards/{id}/link`...

* the order number section is shown although a Card does not have an order number.
* the cancel button says "Cancel payment" which is imprecise.

<img width="479" alt="screen shot 2018-06-14 at 12 27 31" src="https://user-images.githubusercontent.com/191474/41407181-ec7719d2-6fce-11e8-8b19-39ed8f5e30c3.png">

**Comment by ellern** [comment]
The wording after saving a card is not correct. Should be changed to reflect that you have
 saved a card instead of completed a payment.

![screenshot 2018-10-11 at 12 53 53](https://user-images.githubusercontent.com/4930511/46799466-287d1380-cd55-11e8-9faf-06b9a68285ae.png)
