### ISSUE TITLE
Support for iterate variables

### ISSUE THREAD

**Issue by ssandgren** [QuickPay/standard-branding#47]
Eg (below is from customer developer) and they would like to show variables in the payment window with something like this example)

{% for i in (1..10) %}
{% assign keyText = "line"+i %}
{% assign keyPrice = "lineprice"+i %}
{% if model.variables contains keyText and model.variables contains
keyPrice %}
<tr>
<td>{{ model.variables[keyText] }}</td>
<td>kr. {{ model.variables[keyPrice] }}</td>
</tr>
{% endif %}
{% endfor %}

****

**Comment by ta** [comment]
Iteration is supported by Liquid templates https://shopify.github.io/liquid/tags/iteration/ - please describe the exact problem if any

**Comment by ssandgren** [comment]
since it was supported, learn article is updated
